name: Gromacs CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        cd ${{ github.workspace }}
        mkdir build
        cd build
        cmake .. -DGMX_BUILD_OWN_FFTW=ON -DREGRESSIONTEST_DOWNLOAD=ON
        make

    - name: Test
      run: |
        cd ${{ github.workspace }}
        cd build
        make check